// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQaWdVX4FgzOCeme-M4aQmRI2zxtVyxAo',
    appId: '1:467420085734:web:06a9ec3f916b2a9e71aa27',
    messagingSenderId: '467420085734',
    projectId: 'biblioteca-f2d75',
    authDomain: 'biblioteca-f2d75.firebaseapp.com',
    storageBucket: 'biblioteca-f2d75.firebasestorage.app',
    measurementId: 'G-MXEWYFM7K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAadWHU-JBTVGSuzaL8Zg7CJM1c6GqZ3o4',
    appId: '1:467420085734:android:3b64f010b110713171aa27',
    messagingSenderId: '467420085734',
    projectId: 'biblioteca-f2d75',
    storageBucket: 'biblioteca-f2d75.firebasestorage.app',
  );
}
